name: Website Deployment
on:
  push:
    branches:
      - main
jobs:
  Lint:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~./npm
          key: deployment-key-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
  Test:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~./npm
          key: deployment-key-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  Build:
    needs: Test
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  Deploy:
    needs: Build
    runs-on: windows-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: List Files
        run: ls
      - name: Deploy Code
        run: echo "Deploying...."


